update and fix

diff --git a/envs b/envs
--- a/envs
+++ b/envs
@@ -3,8 +3,8 @@
 # envs - manage users_info.json entrys and user-submitted scripts
 # forked from tilde.team
 
-# Copyright 2018-2019, Ben Harris <ben@tilde.team>
-# Copyright 2019, Sven Kinne <creme@envs.net>
+# Copyright 2018, Ben Harris <ben@tilde.team>
+# Copyright 2019-2025, Sven Kinne <creme@envs.net>
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,64 +23,68 @@
 export TERM=xterm-256color
 
 PROGNAME=${0##*/}
-VERSION="0.1.0"
+VERSION="0.1.1"
 
+user="$(whoami)"
+hostname='envs.net'
 INFO_FILE="$HOME/.envs"
 
 ###
 
-clean_up() { # Perform pre-exit housekeeping
-  return
-}
+# check coreutils and wrap stat for portability
+if stat -c"%U" /dev/null >/dev/null 2>/dev/null ; then
+    # GNU environment
+    stat_func () { stat -c '%U' "$1"; }
+else
+    # BSD environment
+    stat_func () { stat -f %Su "$1"; }
+fi
 
+isroot() {
+    [ "$(id -u)" = "0" ]
+}
 
 error_exit() {
   echo -e "${1:-"unknown Error"}" >&2
-  clean_up
   exit 1
 }
-
-
-graceful_exit() {
-  clean_up
-  exit
-}
-
 
 signal_exit() { # Handle trapped signals
   case $1 in
     INT)
-      error_exit "program interrupted by user" ;;
+      error_exit "program interrupted by user"
+      ;;
     TERM)
       printf '\n%s: program terminated\n' "$PROGNAME" >&2
-      graceful_exit ;;
+      exit
+      ;;
     *)
-      error_exit "$PROGNAME: terminating on unknown signal" ;;
+      error_exit "$PROGNAME: terminating on unknown signal"
+      ;;
   esac
 }
 
-
 prompt_confirm() {
   while true; do
-    read -r -n 1 -p "${1:-continue?} [y/n]: " REPLY
-    case "$REPLY" in
-      [yY]) echo ; return 0 ;;
-      [nN]) echo ; return 1 ;;
-      *) printf ' \033[31m %s \n\033[0m' "invalid input"
+    printf "%s [y/n]: " "${1:-continue?}"
+    read -r REPLY
+    case $REPLY in
+      [yY]) printf "\n" ; return 0 ;;
+      [nN]) printf "\n" ; return 1 ;;
+      *) printf " \033[31m %s \n\033[0m" "invalid input" ;;
     esac
   done
 }
-
 
 usage() {
   printf '\n%sUser Scripts%s\n' "$(tput setaf 6)" "$(tput sgr0)"
   printf '\nusage: %s [help|list|submit|about|script_name]\n' "$PROGNAME"
   printf '  %s list                  - show a list of approved userscripts\n' "$PROGNAME"
   printf '  %s submit                - start the submission flow for your own script\n' "$PROGNAME"
-  [[ $(id -u) == 0 ]] && {
+  if isroot; then
     printf '  %s approve               - enter the approval queue\n' "$PROGNAME"
     printf '  %s revoke <script_name>  - send a script back to the author and remove from /envs/bin\n' "$PROGNAME"
-  }
+  fi
   printf '  %s about <script_name>   - get the description for script_name\n' "$PROGNAME"
   printf '  %s <script_name>         - run script_name with all remaining args are passed to the script\n' "$PROGNAME"
 
@@ -99,24 +103,24 @@ usage() {
   fi
 }
 
-
 help_message() {
-  cat <<- EOF
-$(tput setaf 6)$PROGNAME (version $VERSION)$(tput sgr0)
-wrapper for user-submitted scripts and users_info.json entrys
-supports user settings, submission and admin approval
-$(usage)
-EOF
-  return
+  printf "%s%s (version %s)%s\n" "$(tput setaf 6)" "$PROGNAME" "$VERSION" "$(tput sgr0)"
+  printf "wrapper for user-submitted scripts and users_info.json entrys\n"
+  printf "supports user settings, submission and admin approval\n"
+  usage
 }
 
-
 verify_script_name() {
-  [[ $1 == "" ]] && error_exit "please start over and enter the script name"
-  if [[ "$(type "$1" > /dev/null 2>&1)" ]]; then
-    error_exit "$1 already exists. rename your script and try again."
+  [[ -z $1 ]] && error_exit "please start over and enter the script name"
+
+  if command -v "$1"; then
+    if [ "$(command -v "$1")" != "/home/$user/bin/$1" ]; then
+      error_exit "$1 already exists. rename your script and try again."
+    fi
   fi
+
   [[ -x /envs/bin/"$1" ]] && error_exit "$1 is already taken. rename your script and try again."
+
   case "$1" in
     help|about|description|desc|list|ls|submit|apropos|approve|revoke|show|edit|get|set|unset)
       error_exit "$1 is a subcommand of envs. rename your script and try again.";;
@@ -124,7 +128,6 @@ verify_script_name() {
       return;;
   esac
 }
-
 
 submission_checklist() {
   cat <<- EOF
@@ -138,14 +141,13 @@ requirements for submitting a user script or program:
 EOF
 }
 
-
 mail_body() {
   cat <<- EOF
-Subject: envs script submission from $USER
-From: $USER@envs.net
-To: creme@envs.net
+Subject: envs script submission from ${user}
+From: ${user}@${hostname}
+To: creme@${hostname}
 
-envs script submission from $USER
+envs script submission from ${user}
 
 script name: $1
 
@@ -155,7 +157,7 @@ description:
 $2
 
 -----------------------------------------------------------------------
-you'll find the script and description in: /envs/pending-submissions/$USER/$1
+you'll find the script and description in: /envs/pending-submissions/$user/$1
 
 run this to see the approval queue:
 sudo envs approve
@@ -209,16 +211,14 @@ fi
 [ "$(envs_get desc)" == '' ] && envs_set desc 'a short describtion or message'
 [ "$(envs_get ssh_pubkey)" == '' ] && envs_set ssh_pubkey 0
 
-
 # Trap signals
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT"  INT
 
-
 # Parse command-line
 case "$1" in
   -h | --help | help)
-    help_message; graceful_exit
+    help_message; exit
   ;;
 
   -v | --version)
@@ -230,15 +230,16 @@ case "$1" in
     error_exit "Unknown option $1"
   ;;
 
-
   list | ls)
     printf 'available scripts:\n\n'
     for scr in /envs/bin/*; do
-      script_name=$(basename "$scr")
-      target=$(readlink -f "$scr")
-      printf '%s%s by %s%s\n' "$(tput setaf 6)" "$script_name" "$(stat -c '%U' "$target")" "$(tput sgr0)"
-      cat /envs/descriptions/"$script_name"
-      printf '\n'
+      if [ -f "$scr" ]; then
+        script_name=$(basename "$scr")
+        target=$(readlink -f "$scr")
+        printf '%s%s by %s%s\n' "$(tput setaf 6)" "$script_name" "$(stat_func "$target")" "$(tput sgr0)"
+        cat /envs/descriptions/"$script_name"
+        printf '\n'
+      fi
     done
   ;;
 
@@ -251,9 +252,9 @@ case "$1" in
   ;;
 
   submit)
-    printf "hello, %s! so it's time to submit your script?\n" "$USER"
+    printf "hello, %s! so it's time to submit your script?\n" "$user"
     submission_checklist
-    prompt_confirm "are you ready to continue?" || graceful_exit
+    prompt_confirm "are you ready to continue?" || exit
     printf 'enter the name of your script: '
     read -r script_name
 
@@ -261,7 +262,7 @@ case "$1" in
 
     if [[ -x "$HOME"/bin/"$script_name" ]]; then
       printf '\ncool, found your script\n'
-      [[ -x /envs/pending-submissions/"$USER"/"$script_name"/"$script_name" ]] && error_exit "you've already submitted $script_name"
+      [[ -x /envs/pending-submissions/"$user"/"$script_name"/"$script_name" ]] && error_exit "you've already submitted $script_name"
     else
       error_exit "$script_name not found in ~/bin"
     fi
@@ -269,18 +270,20 @@ case "$1" in
     printf 'enter a description of your script:\n'
     read -r description
     printf '\nyour script, along with your description will be sent to the admins for approval\n'
-    prompt_confirm "ready to submit?" || graceful_exit
+    prompt_confirm "ready to submit?" || exit
 
     # submit now
-    mkdir -p /envs/pending-submissions/"$USER"/"$script_name"
-    ln -s "$HOME"/bin/"$script_name" /envs/pending-submissions/"$USER"/"$script_name"/"$script_name"
-    echo "$description" > /envs/pending-submissions/"$USER"/"$script_name"/description.txt
+    mkdir -p /envs/pending-submissions/"$user"/"$script_name"
+    ln -s "$HOME"/bin/"$script_name" /envs/pending-submissions/"$user"/"$script_name"/"$script_name"
+    printf "%s\n" "$description" > /envs/pending-submissions/"$user"/"$script_name"/description.txt
     mail_body "$script_name" "$description" | /usr/sbin/sendmail creme
     printf 'script submitted. thanks! :)\n'
   ;;
 
   approve)
-    [[ $(id -u) != 0 ]] && error_exit "re-run this as sudo to access the approval queue"
+    if ! isroot; then
+      error_exit "re-run this as sudo to access the approval queue"
+    fi
 
     printf 'welcome to the approval queue\n\n'
 
@@ -290,38 +293,40 @@ case "$1" in
         script_name="$(basename "$scr")"
         [[ -f $scr/approved ]] && continue
         script="$scr"/"$script_name"
-        printf '%s by %s\n' "$script_name" "$user"
-        cat "$scr"/description.txt
-        prompt_confirm "approve?" || continue
 
-        sudo ln -s "$(readlink -f "$script")" /envs/bin/"$script_name"
-        sudo cp "$scr"/description.txt /envs/descriptions/"$script_name"
-        sudo touch "$scr"/approved
-        sudo chmod -R 664 /envs/descriptions ; sudo chmod 755 /envs/descriptions
-        sudo chown -R root:envs /envs/descriptions /envs/bin
-        echo "your submission of $script_name has been approved and is now available at /envs/bin/$script_name" | /usr/sbin/sendmail "$user"
+        if [ -f "$script" ]; then
+          printf '%s by %s\n' "$script_name" "$user"
+          cat "$scr"/description.txt
+          prompt_confirm "approve?" || continue
+
+          ln -s "$(readlink -f "$script")" /envs/bin/"$script_name"
+          cp "$scr"/description.txt /envs/descriptions/"$script_name"
+          touch "$scr"/approved
+          chmod -R 664 /envs/descriptions ; chmod 755 /envs/descriptions
+          chown -R root:envs /envs/descriptions /envs/bin
+          printf "your submission of %s has been approved and is now available at /envs/bin/%s" "$script_name" "$script_name" | /usr/sbin/sendmail "$user"
+        fi
       done
     done
-    echo "~~done for now~~"
+    printf "~~done for now~~\n"
   ;;
 
   revoke)
-    [[ "$(id -u)" != 0 ]] && error_exit "re-run this as sudo to access the revoke menu"
-    [[ -f /envs/bin/"$2" ]] || error_exit "$2 isn't an approved script"
+    isroot || error_exit "re-run this as sudo to access the revoke menu"
+    [ -f /envs/bin/"$2" ] || error_exit "$2 isn't an approved script"
 
     prompt_confirm "revoke $2?"
     printf 'please provide a reason: '
     read -r reason
 
     original_script="$(readlink -f /envs/bin/"$2")"
-    author="$(stat -c '%U' "$original_script")"
-    sudo rm /envs/{bin,descriptions}/"$2"
-    sudo rm -rf /envs/pending-submissions/"$author"/"$2"
+    author="$(stat_func "$original_script")"
+    rm /envs/{bin,descriptions}/"$2"
+    rm -rf /envs/pending-submissions/"$author"/"$2"
 
-    echo -e "your script $2 has been returned because: $reason\nfeel free to resubmit" | /usr/sbin/sendmail "$author"
+    printf "your script %s has been returned because: %s\nfeel free to resubmit\n" "$2" "$reason" | /usr/sbin/sendmail "$author"
     printf '%s revoked and returned to author\n' "$2"
   ;;
-
 
   show) envs_show ;;
 
@@ -333,20 +338,22 @@ case "$1" in
 
   unset) envs_unset "$2" ;;
 
-
   *)
-    if [[ -f /envs/bin/"$1" ]]; then
-      prog=/envs/bin/"$1"
+    if [ -z "$1" ]; then
+      help_message
+      exit
+    elif [ -x /envs/bin/"$1" ]; then
+      prog="/envs/bin/$1"
       shift
-      $prog "$@"
-      graceful_exit
+      exec $prog "$@"
     else
-      [[ "$1" == "" ]] || printf "%s not found. try %s list to see what's available\n" "$1" "$PROGNAME"
-      help_message; graceful_exit;
+      printf "%s not found. try %s list to see what's available\n" "$1" "$PROGNAME"
+      help_message
+      exit
     fi
   ;;
 
 esac
 
 #
-graceful_exit
+exit
